/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
    const group = useRef();
    const { nodes, materials } = useGLTF('/Flower.glb');

    return (
        <group scale={15} ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.Blossom.geometry} material={materials.Blossom} rotation={[Math.PI / 2, 0, 0]} scale={1.22} />
            <mesh geometry={nodes.Stem.geometry} material={materials.Stem} rotation={[Math.PI / 2, 0, 0]} scale={1.22} />
        </group>
    )
}
